<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF14%20Pareto%20Analysis%20(80-20%20Rule).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [11]:
CustomerSales = df.groupby(['Customer_Name','Customer_ID'])['Sales'].sum().reset_index(name='TotalSales')
CustomerSales.head()

     Customer_Name Customer_ID  TotalSales
0    Aaron Bergman    AB-10015     886.156
1    Aaron Hawkins    AH-10030    1744.700
2   Aaron Smayling    AS-10045    3050.692
3  Adam Bellavance    AB-10060    7755.620
4        Adam Hart    AH-10075    3250.337

In [25]:
CustomerSales = CustomerSales.sort_values(by = 'TotalSales', ascending = False).reset_index(drop=True)
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,687
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,731
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,623
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,758
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,7
...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,657
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,546
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,124
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,456
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,738

In [26]:
grand_Total= CustomerSales['TotalSales'].sum()
grand_Total

np.float64(2297200.8603000003)

In [27]:
CustomerSales['RunningSales']= CustomerSales['TotalSales'].cumsum().round(2)
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,687
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,731
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,623
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,758
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,7
...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,657
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,546
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,124
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,456
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,738

In [28]:
CustomerSales['CumulativePctSales'] = CustomerSales['RunningSales']/grand_Total
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,687
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,731
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,623
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,758
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,7
...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,657
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,546
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,124
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,456
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,738

In [29]:
CustomerSales['CustomerRank'] = CustomerSales.index + 1
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,1
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,2
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,3
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,4
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,5
...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,789
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,790
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,791
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,792
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,793

In [31]:
TotalCustomers = len(CustomerSales)
TotalCustomers

793

In [33]:
CustomerSales['CumulativePctCustomers']= (CustomerSales['CustomerRank']/TotalCustomers *100).round(2)
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank,CumulativePctCustomers
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,1,0.13
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,2,0.25
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,3,0.38
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,4,0.50
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,5,0.63
...,...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,789,99.50
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,790,99.62
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,791,99.75
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,792,99.87
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,793,100.00

In [34]:
CustomerSales['ParetoGroup'] = CustomerSales['CumulativePctCustomers'].apply(lambda x: 'Top 80%' if x <= 80 else 'Botton 20%')
CustomerSales

,Customer_Name,Customer_ID,TotalSales,RunningSales,CumulativePctSales,CustomerRank,CumulativePctCustomers,ParetoGroup
0,Sean Miller,SM-20320,25043.050,25043.05,0.010902,1,0.13,Top 80%
1,Tamara Chand,TC-20980,19052.218,44095.27,0.019195,2,0.25,Top 80%
2,Raymond Buch,RB-19360,15117.339,59212.61,0.025776,3,0.38,Top 80%
3,Tom Ashbrook,TA-21385,14595.620,73808.23,0.032130,4,0.50,Top 80%
4,Adrian Barton,AB-10105,14473.571,88281.80,0.038430,5,0.63,Top 80%
...,...,...,...,...,...,...,...,...
788,Roy Skaria,RS-19870,22.328,2297157.46,0.999981,789,99.50,Botton 20%
789,Mitch Gastineau,MG-18205,16.739,2297174.20,0.999988,790,99.62,Botton 20%
790,Carl Jackson,CJ-11875,16.520,2297190.72,0.999996,791,99.75,Botton 20%
791,Lela Donovan,LD-16855,5.304,2297196.03,0.999998,792,99.87,Botton 20%
792,Thais Sissman,TS-21085,4.833,2297200.86,1.000000,793,100.00,Botton 20%