<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF3%20Month-over-Month%20Sales%20Growth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel(r'/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Mounted at /content/drive

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['SalesMonth'] = df['Order_Date'].dt.to_period('M')
df['SalesMonth2'] = df['Order_Date'].dt.month
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,SalesMonth,SalesMonth2
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016-11,11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016-11,11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016-06,6
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015-10,10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015-10,10

In [ ]:
monthly_sales= df.groupby('SalesMonth')['Sales'].sum().reset_index().sort_values('SalesMonth')
monthly_sales

   SalesMonth        Sales
0     2014-01   14236.8950
1     2014-02    4519.8920
2     2014-03   55691.0090
3     2014-04   28295.3450
4     2014-05   23648.2870
5     2014-06   34595.1276
6     2014-07   33946.3930
7     2014-08   27909.4685
8     2014-09   81777.3508
9     2014-10   31453.3930
10    2014-11   78628.7167
11    2014-12   69545.6205
12    2015-01   18174.0756
13    2015-02   11951.4110
14    2015-03   38726.2520
15    2015-04   34195.2085
16    2015-05   30131.6865
17    2015-06   24797.2920
18    2015-07   28765.3250
19    2015-08   36898.3322
20    2015-09   64595.9180
21    2015-10   31404.9235
22    2015-11   75972.5635
23    2015-12   74919.5212
24    2016-01   18542.4910
25    2016-02   22978.8150
26    2016-03   51715.8750
27    2016-04   38750.0390
28    2016-05   56987.7280
29    2016-06   40344.5340
30    2016-07   39261.9630
31    2016-08   31115.3743
32    2016-09   73410.0249
33    2016-10   59687.7450
34    2016-11   79411.9658
35    2016-12   96999.0430
36    2017-01   43971.3740
37    2017-02   20301.1334
38    2017-03   58872.3528
39    2017-04   36521.5361
40    2017-05   44261.1102
41    2017-06   52981.7257
42    2017-07   45264.4160
43    2017-08   63120.8880
44    2017-09   87866.6520
45    2017-10   77776.9232
46    2017-11  118447.8250
47    2017-12   83829.3188

In [ ]:
monthly_sales['PrevMOnthSales'] = monthly_sales['Sales'].shift(1)
monthly_sales

   SalesMonth        Sales  PrevMOnthSales
0     2014-01   14236.8950             NaN
1     2014-02    4519.8920      14236.8950
2     2014-03   55691.0090       4519.8920
3     2014-04   28295.3450      55691.0090
4     2014-05   23648.2870      28295.3450
5     2014-06   34595.1276      23648.2870
6     2014-07   33946.3930      34595.1276
7     2014-08   27909.4685      33946.3930
8     2014-09   81777.3508      27909.4685
9     2014-10   31453.3930      81777.3508
10    2014-11   78628.7167      31453.3930
11    2014-12   69545.6205      78628.7167
12    2015-01   18174.0756      69545.6205
13    2015-02   11951.4110      18174.0756
14    2015-03   38726.2520      11951.4110
15    2015-04   34195.2085      38726.2520
16    2015-05   30131.6865      34195.2085
17    2015-06   24797.2920      30131.6865
18    2015-07   28765.3250      24797.2920
19    2015-08   36898.3322      28765.3250
20    2015-09   64595.9180      36898.3322
21    2015-10   31404.9235      64595.9180
22    2015-11   75972.5635      31404.9235
23    2015-12   74919.5212      75972.5635
24    2016-01   18542.4910      74919.5212
25    2016-02   22978.8150      18542.4910
26    2016-03   51715.8750      22978.8150
27    2016-04   38750.0390      51715.8750
28    2016-05   56987.7280      38750.0390
29    2016-06   40344.5340      56987.7280
30    2016-07   39261.9630      40344.5340
31    2016-08   31115.3743      39261.9630
32    2016-09   73410.0249      31115.3743
33    2016-10   59687.7450      73410.0249
34    2016-11   79411.9658      59687.7450
35    2016-12   96999.0430      79411.9658
36    2017-01   43971.3740      96999.0430
37    2017-02   20301.1334      43971.3740
38    2017-03   58872.3528      20301.1334
39    2017-04   36521.5361      58872.3528
40    2017-05   44261.1102      36521.5361
41    2017-06   52981.7257      44261.1102
42    2017-07   45264.4160      52981.7257
43    2017-08   63120.8880      45264.4160
44    2017-09   87866.6520      63120.8880
45    2017-10   77776.9232      87866.6520
46    2017-11  118447.8250      77776.9232
47    2017-12   83829.3188     118447.8250

In [ ]:
monthly_sales['Mom_Growth_pct'] = ((monthly_sales['Sales']-monthly_sales['PrevMOnthSales'])*100 / monthly_sales['PrevMOnthSales']).round(2)
monthly_sales

   SalesMonth        Sales  PrevMOnthSales  Mom_Growth_pct
0     2014-01   14236.8950             NaN             NaN
1     2014-02    4519.8920      14236.8950          -68.25
2     2014-03   55691.0090       4519.8920         1132.13
3     2014-04   28295.3450      55691.0090          -49.19
4     2014-05   23648.2870      28295.3450          -16.42
5     2014-06   34595.1276      23648.2870           46.29
6     2014-07   33946.3930      34595.1276           -1.88
7     2014-08   27909.4685      33946.3930          -17.78
8     2014-09   81777.3508      27909.4685          193.01
9     2014-10   31453.3930      81777.3508          -61.54
10    2014-11   78628.7167      31453.3930          149.98
11    2014-12   69545.6205      78628.7167          -11.55
12    2015-01   18174.0756      69545.6205          -73.87
13    2015-02   11951.4110      18174.0756          -34.24
14    2015-03   38726.2520      11951.4110          224.03
15    2015-04   34195.2085      38726.2520          -11.70
16    2015-05   30131.6865      34195.2085          -11.88
17    2015-06   24797.2920      30131.6865          -17.70
18    2015-07   28765.3250      24797.2920           16.00
19    2015-08   36898.3322      28765.3250           28.27
20    2015-09   64595.9180      36898.3322           75.06
21    2015-10   31404.9235      64595.9180          -51.38
22    2015-11   75972.5635      31404.9235          141.91
23    2015-12   74919.5212      75972.5635           -1.39
24    2016-01   18542.4910      74919.5212          -75.25
25    2016-02   22978.8150      18542.4910           23.93
26    2016-03   51715.8750      22978.8150          125.06
27    2016-04   38750.0390      51715.8750          -25.07
28    2016-05   56987.7280      38750.0390           47.06
29    2016-06   40344.5340      56987.7280          -29.20
30    2016-07   39261.9630      40344.5340           -2.68
31    2016-08   31115.3743      39261.9630          -20.75
32    2016-09   73410.0249      31115.3743          135.93
33    2016-10   59687.7450      73410.0249          -18.69
34    2016-11   79411.9658      59687.7450           33.05
35    2016-12   96999.0430      79411.9658           22.15
36    2017-01   43971.3740      96999.0430          -54.67
37    2017-02   20301.1334      43971.3740          -53.83
38    2017-03   58872.3528      20301.1334          190.00
39    2017-04   36521.5361      58872.3528          -37.96
40    2017-05   44261.1102      36521.5361           21.19
41    2017-06   52981.7257      44261.1102           19.70
42    2017-07   45264.4160      52981.7257          -14.57
43    2017-08   63120.8880      45264.4160           39.45
44    2017-09   87866.6520      63120.8880           39.20
45    2017-10   77776.9232      87866.6520          -11.48
46    2017-11  118447.8250      77776.9232           52.29
47    2017-12   83829.3188     118447.8250          -29.23