<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF4%20Month_Moving_Average_of_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel(r'/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Mounted at /content/drive

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df['Order_Date']= pd.to_datetime(df['Order_Date'])
df['Sales_Month']= df['Order_Date'].dt.to_period('M')
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Sales_Month
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016-11
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016-11
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016-06
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015-10
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015-10

In [ ]:
Monthly_Sales = df.groupby('Sales_Month')['Sales'].sum().reset_index()
Monthly_Sales

   Sales_Month        Sales
0      2014-01   14236.8950
1      2014-02    4519.8920
2      2014-03   55691.0090
3      2014-04   28295.3450
4      2014-05   23648.2870
5      2014-06   34595.1276
6      2014-07   33946.3930
7      2014-08   27909.4685
8      2014-09   81777.3508
9      2014-10   31453.3930
10     2014-11   78628.7167
11     2014-12   69545.6205
12     2015-01   18174.0756
13     2015-02   11951.4110
14     2015-03   38726.2520
15     2015-04   34195.2085
16     2015-05   30131.6865
17     2015-06   24797.2920
18     2015-07   28765.3250
19     2015-08   36898.3322
20     2015-09   64595.9180
21     2015-10   31404.9235
22     2015-11   75972.5635
23     2015-12   74919.5212
24     2016-01   18542.4910
25     2016-02   22978.8150
26     2016-03   51715.8750
27     2016-04   38750.0390
28     2016-05   56987.7280
29     2016-06   40344.5340
30     2016-07   39261.9630
31     2016-08   31115.3743
32     2016-09   73410.0249
33     2016-10   59687.7450
34     2016-11   79411.9658
35     2016-12   96999.0430
36     2017-01   43971.3740
37     2017-02   20301.1334
38     2017-03   58872.3528
39     2017-04   36521.5361
40     2017-05   44261.1102
41     2017-06   52981.7257
42     2017-07   45264.4160
43     2017-08   63120.8880
44     2017-09   87866.6520
45     2017-10   77776.9232
46     2017-11  118447.8250
47     2017-12   83829.3188

In [ ]:
Monthly_Sales = Monthly_Sales.sort_values('Sales_Month').reset_index(drop=True)
Monthly_Sales

   Sales_Month        Sales
0      2014-01   14236.8950
1      2014-02    4519.8920
2      2014-03   55691.0090
3      2014-04   28295.3450
4      2014-05   23648.2870
5      2014-06   34595.1276
6      2014-07   33946.3930
7      2014-08   27909.4685
8      2014-09   81777.3508
9      2014-10   31453.3930
10     2014-11   78628.7167
11     2014-12   69545.6205
12     2015-01   18174.0756
13     2015-02   11951.4110
14     2015-03   38726.2520
15     2015-04   34195.2085
16     2015-05   30131.6865
17     2015-06   24797.2920
18     2015-07   28765.3250
19     2015-08   36898.3322
20     2015-09   64595.9180
21     2015-10   31404.9235
22     2015-11   75972.5635
23     2015-12   74919.5212
24     2016-01   18542.4910
25     2016-02   22978.8150
26     2016-03   51715.8750
27     2016-04   38750.0390
28     2016-05   56987.7280
29     2016-06   40344.5340
30     2016-07   39261.9630
31     2016-08   31115.3743
32     2016-09   73410.0249
33     2016-10   59687.7450
34     2016-11   79411.9658
35     2016-12   96999.0430
36     2017-01   43971.3740
37     2017-02   20301.1334
38     2017-03   58872.3528
39     2017-04   36521.5361
40     2017-05   44261.1102
41     2017-06   52981.7257
42     2017-07   45264.4160
43     2017-08   63120.8880
44     2017-09   87866.6520
45     2017-10   77776.9232
46     2017-11  118447.8250
47     2017-12   83829.3188

In [ ]:
Monthly_Sales['Moving_Average_3Months'] = (Monthly_Sales['Sales'].rolling(window=3,min_periods=1).mean().round(2))
Monthly_Sales

   Sales_Month        Sales  Moving_Average_3Months
0      2014-01   14236.8950                14236.90
1      2014-02    4519.8920                 9378.39
2      2014-03   55691.0090                24815.93
3      2014-04   28295.3450                29502.08
4      2014-05   23648.2870                35878.21
5      2014-06   34595.1276                28846.25
6      2014-07   33946.3930                30729.94
7      2014-08   27909.4685                32150.33
8      2014-09   81777.3508                47877.74
9      2014-10   31453.3930                47046.74
10     2014-11   78628.7167                63953.15
11     2014-12   69545.6205                59875.91
12     2015-01   18174.0756                55449.47
13     2015-02   11951.4110                33223.70
14     2015-03   38726.2520                22950.58
15     2015-04   34195.2085                28290.96
16     2015-05   30131.6865                34351.05
17     2015-06   24797.2920                29708.06
18     2015-07   28765.3250                27898.10
19     2015-08   36898.3322                30153.65
20     2015-09   64595.9180                43419.86
21     2015-10   31404.9235                44299.72
22     2015-11   75972.5635                57324.47
23     2015-12   74919.5212                60765.67
24     2016-01   18542.4910                56478.19
25     2016-02   22978.8150                38813.61
26     2016-03   51715.8750                31079.06
27     2016-04   38750.0390                37814.91
28     2016-05   56987.7280                49151.21
29     2016-06   40344.5340                45360.77
30     2016-07   39261.9630                45531.41
31     2016-08   31115.3743                36907.29
32     2016-09   73410.0249                47929.12
33     2016-10   59687.7450                54737.71
34     2016-11   79411.9658                70836.58
35     2016-12   96999.0430                78699.58
36     2017-01   43971.3740                73460.79
37     2017-02   20301.1334                53757.18
38     2017-03   58872.3528                41048.29
39     2017-04   36521.5361                38565.01
40     2017-05   44261.1102                46551.67
41     2017-06   52981.7257                44588.12
42     2017-07   45264.4160                47502.42
43     2017-08   63120.8880                53789.01
44     2017-09   87866.6520                65417.32
45     2017-10   77776.9232                76254.82
46     2017-11  118447.8250                94697.13
47     2017-12   83829.3188                93351.36