<a href="https://colab.research.google.com/github/shijithpulikkal/CodingFactory/blob/main/CF8%20Cumulative%20Distinct%20Customers%20Over%20Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Superstore.xlsx')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df = df.sort_values('Order_Date')
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
7980,7981,CA-2014-103800,2014-01-03,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
739,740,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
740,741,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
741,742,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
1759,1760,CA-2014-141817,2014-01-05,2014-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [ ]:
first_seen = df.drop_duplicates(subset = 'Customer_ID', keep = 'first').copy()
first_seen['Sales_Month'] = first_seen['Order_Date'].dt.to_period('M')
first_seen

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit,Sales_Month
7980,7981,CA-2014-103800,2014-01-03,2014-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512,2014-01
739,740,CA-2014-112326,2014-01-04,2014-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717,2014-01
1759,1760,CA-2014-141817,2014-01-05,2014-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840,2014-01
7476,7477,CA-2014-167199,2014-01-06,2014-01-10,Standard Class,ME-17320,Maria Etezadi,Home Office,United States,Henderson,...,South,OFF-AR-10001662,Office Supplies,Art,Rogers Handheld Barrel Pencil Sharpener,5.480,2,0.0,1.4796,2014-01
7180,7181,CA-2014-106054,2014-01-06,2014-01-07,First Class,JO-15145,Jack O'Briant,Corporate,United States,Athens,...,South,OFF-AR-10002399,Office Supplies,Art,"Dixon Prang Watercolor Pencils, 10-Color Set w...",12.780,3,0.0,5.2398,2014-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1620,1621,CA-2017-108560,2017-07-08,2017-07-15,Standard Class,JC-15385,Jenna Caffey,Consumer,United States,Kent,...,West,FUR-FU-10002937,Furniture,Furnishings,"GE 48"" Fluorescent Tube, Cool White Energy Sav...",198.460,2,0.0,99.2300,2017-07
6755,6756,CA-2017-124205,2017-09-15,2017-09-19,Standard Class,TC-21145,Theresa Coyne,Corporate,United States,Lakewood,...,East,FUR-FU-10002445,Furniture,Furnishings,"DAX Two-Tone Rosewood/Black Document Frame, De...",47.400,5,0.0,18.9600,2017-09
526,527,CA-2017-113558,2017-10-21,2017-10-26,Standard Class,PH-18790,Patricia Hirasaki,Home Office,United States,Lakeland,...,South,FUR-CH-10003379,Furniture,Chairs,Global Commerce Series High-Back Swivel/Tilt C...,683.952,3,0.2,42.7470,2017-10
1260,1261,CA-2017-117079,2017-10-23,2017-10-27,Standard Class,JR-15700,Jocasta Rupert,Consumer,United States,Jacksonville,...,South,TEC-PH-10004586,Technology,Phones,Wilson SignalBoost 841262 DB PRO Amplifier Kit,863.880,3,0.2,107.9850,2017-10
9473,9474,CA-2017-102925,2017-11-05,2017-11-10,Second Class,CD-12280,Christina DeMoss,Consumer,United States,New York City,...,East,FUR-FU-10004245,Furniture,Furnishings,"Career Cubicle Clock, 8 1/4"", Black",101.400,5,0.0,38.5320,2017-11

In [ ]:
new_customers_per_month = (first_seen.groupby('Sales_Month')['Customer_ID'].count().reset_index(name='NewCustomers'))
new_customers_per_month

   Sales_Month  NewCustomers
0      2014-01            32
1      2014-02            24
2      2014-03            65
3      2014-04            56
4      2014-05            56
5      2014-06            48
6      2014-07            44
7      2014-08            49
8      2014-09            68
9      2014-10            42
10     2014-11            62
11     2014-12            49
12     2015-01             7
13     2015-02             7
14     2015-03            18
15     2015-04            12
16     2015-05            12
17     2015-06            12
18     2015-07             8
19     2015-08            12
20     2015-09            16
21     2015-10             9
22     2015-11            10
23     2015-12            13
24     2016-01             6
25     2016-02             2
26     2016-03             6
27     2016-04             7
28     2016-05             7
29     2016-06             8
30     2016-07             2
31     2016-08             4
32     2016-10             1
33     2016-11             6
34     2016-12             2
35     2017-03             3
36     2017-04             1
37     2017-06             1
38     2017-07             2
39     2017-09             1
40     2017-10             2
41     2017-11             1

In [ ]:
new_customers_per_month['CumulativeDistinctCustomers'] = new_customers_per_month['NewCustomers'].cumsum()
new_customers_per_month

   Sales_Month  NewCustomers  CumulativeDistinctCustomers
0      2014-01            32                           32
1      2014-02            24                           56
2      2014-03            65                          121
3      2014-04            56                          177
4      2014-05            56                          233
5      2014-06            48                          281
6      2014-07            44                          325
7      2014-08            49                          374
8      2014-09            68                          442
9      2014-10            42                          484
10     2014-11            62                          546
11     2014-12            49                          595
12     2015-01             7                          602
13     2015-02             7                          609
14     2015-03            18                          627
15     2015-04            12                          639
16     2015-05            12                          651
17     2015-06            12                          663
18     2015-07             8                          671
19     2015-08            12                          683
20     2015-09            16                          699
21     2015-10             9                          708
22     2015-11            10                          718
23     2015-12            13                          731
24     2016-01             6                          737
25     2016-02             2                          739
26     2016-03             6                          745
27     2016-04             7                          752
28     2016-05             7                          759
29     2016-06             8                          767
30     2016-07             2                          769
31     2016-08             4                          773
32     2016-10             1                          774
33     2016-11             6                          780
34     2016-12             2                          782
35     2017-03             3                          785
36     2017-04             1                          786
37     2017-06             1                          787
38     2017-07             2                          789
39     2017-09             1                          790
40     2017-10             2                          792
41     2017-11             1                          793